repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml

# https://flake8.pycqa.org/en/latest/user/using-hooks.html
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        # GitHub editor is 127 chars wide, see workflows in .github/
        args: [
            "--select=E9,F63,F7,F82",
            "--max-line-length=127"
        ]

# https://black.readthedocs.io/en/stable/integrations/source_version_control.html
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
    -   id: black
        language_version: python3.13
        # GitHub editor is 127 chars wide, see workflows in .github/
        args: ["--line-length=127"]
